# Generated by Django 4.1.5 on 2023-03-14 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название факультета')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('intramural', models.BooleanField(default=True, verbose_name='Очное обучение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('budgets', models.PositiveIntegerField(verbose_name='Количестов бюджетных мест')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите короткое название вашего мероприятия', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание вашего мероприятия. Укажите чего стоит ожидать посетителям, сколько это займет по времени и как вы собираетесь проводить время на этом этапе.', max_length=2000, verbose_name='Описание')),
                ('required', models.BooleanField(default=True, verbose_name='Регистрация обязательна')),
                ('online', models.BooleanField(default=True, verbose_name='Это онлайн встреча?')),
                ('place', models.CharField(help_text='Введите адрес проведения (можно ссылку).', max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Квалификация')),
            ],
        ),
        migrations.CreateModel(
            name='Schoolsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/documents/syllabs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dot', 'docx', 'doc', 'pdf'])], verbose_name='Прикрепить учебный план')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=200, null=True, verbose_name='Отчество')),
                ('description', models.TextField(max_length=500, verbose_name='О себе')),
                ('directions', models.ManyToManyField(blank=True, to='catalog.direction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, verbose_name='Коментарий')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Оценка')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название факультета')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('adres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255)),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Examset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(verbose_name='Минимальная оценка')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательный экзамен')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.direction')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.schoolsubject')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.teacher'),
        ),
        migrations.AddField(
            model_name='direction',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='catalog.teacher', verbose_name=''),
        ),
        migrations.AddField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.faculty'),
        ),
        migrations.AddField(
            model_name='direction',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.qualification'),
        ),
        migrations.AddField(
            model_name='direction',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.syllabus'),
        ),
    ]
