# Generated by Django 4.1.3 on 2023-03-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_direction_syllabus_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='years',
            field=models.PositiveIntegerField(default=4, verbose_name='Срок обучения '),
            preserve_default=False,
        ),
    ]
