# Generated by Django 4.1.3 on 2023-03-15 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_direction_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='ofline',
            field=models.BooleanField(default=True, verbose_name='Есть очные группы'),
        ),
        migrations.AddField(
            model_name='direction',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Есть заочные группы'),
        ),
        migrations.AddField(
            model_name='direction',
            name='payed',
            field=models.PositiveIntegerField(default=80, verbose_name='Количестов платных мест'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator', to='catalog.teacher', verbose_name=''),
        ),
    ]
