# Generated by Django 4.1.3 on 2023-03-15 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_direction_intramural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.teacher'),
        ),
    ]
